export const CODE_SNIPPETS = {
  'bubble-sort': {
    cpp: [
      'void bubbleSort(int arr[], int n) {',
      '  for (int i = 0; i < n-1; i++) {',
      '    bool swapped = false;',
      '    for (int j = 0; j < n-i-1; j++) {',
      '      if (arr[j] > arr[j+1]) {',
      '        swap(arr[j], arr[j+1]);',
      '        swapped = true;',
      '      }',
      '    }',
      '    if (!swapped) break;',
      '  }',
      '}',
    ],
    python: [
      'def bubble_sort(arr):',
      '    n = len(arr)',
      '    for i in range(n-1):',
      '        swapped = False',
      '        for j in range(n-i-1):',
      '            if arr[j] > arr[j+1]:',
      '                arr[j], arr[j+1] = arr[j+1], arr[j]',
      '                swapped = True',
      '        if not swapped:',
      '            break',
      '    return arr',
    ],
  },
  'selection-sort': {
    cpp: [
      'void selectionSort(int arr[], int n) {',
      '  for (int i = 0; i < n-1; i++) {',
      '    int minIdx = i;',
      '    for (int j = i+1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx])',
      '        minIdx = j;',
      '    }',
      '    if (minIdx != i)',
      '      swap(arr[i], arr[minIdx]);',
      '  }',
      '}',
    ],
    python: [
      'def selection_sort(arr):',
      '    n = len(arr)',
      '    for i in range(n-1):',
      '        min_idx = i',
      '        for j in range(i+1, n):',
      '            if arr[j] < arr[min_idx]:',
      '                min_idx = j',
      '        if min_idx != i:',
      '            arr[i], arr[min_idx] = arr[min_idx], arr[i]',
      '    return arr',
    ],
  },
  'insertion-sort': {
    cpp: [
      'void insertionSort(int arr[], int n) {',
      '  for (int i = 1; i < n; i++) {',
      '    int key = arr[i];',
      '    int j = i - 1;',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j+1] = arr[j];',
      '      j--;',
      '    }',
      '    arr[j+1] = key;',
      '  }',
      '}',
    ],
    python: [
      'def insertion_sort(arr):',
      '    for i in range(1, len(arr)):',
      '        key = arr[i]',
      '        j = i - 1',
      '        while j >= 0 and arr[j] > key:',
      '            arr[j+1] = arr[j]',
      '            j -= 1',
      '        arr[j+1] = key',
      '    return arr',
    ],
  },
  'merge-sort': {
    cpp: [
      'void merge(int arr[], int l, int m, int r) {',
      '  int n1=m-l+1, n2=r-m;',
      '  int L[n1], R[n2];',
      '  for(int i=0;i<n1;i++) L[i]=arr[l+i];',
      '  for(int j=0;j<n2;j++) R[j]=arr[m+1+j];',
      '  int i=0,j=0,k=l;',
      '  while(i<n1 && j<n2) {',
      '    if(L[i]<=R[j]) arr[k++]=L[i++];',
      '    else arr[k++]=R[j++];',
      '  }',
      '  while(i<n1) arr[k++]=L[i++];',
      '  while(j<n2) arr[k++]=R[j++];',
      '}',
      'void mergeSort(int arr[], int l, int r) {',
      '  if(l<r) {',
      '    int m=l+(r-l)/2;',
      '    mergeSort(arr,l,m);',
      '    mergeSort(arr,m+1,r);',
      '    merge(arr,l,m,r);',
      '  }',
      '}',
    ],
    python: [
      'def merge_sort(arr):',
      '    if len(arr) <= 1:',
      '        return arr',
      '    mid = len(arr) // 2',
      '    left = merge_sort(arr[:mid])',
      '    right = merge_sort(arr[mid:])',
      '    return merge(left, right)',
      '',
      'def merge(left, right):',
      '    result = []',
      '    i = j = 0',
      '    while i < len(left) and j < len(right):',
      '        if left[i] <= right[j]:',
      '            result.append(left[i]); i += 1',
      '        else:',
      '            result.append(right[j]); j += 1',
      '    return result + left[i:] + right[j:]',
    ],
  },
  'quick-sort': {
    cpp: [
      'int partition(int arr[], int low, int high) {',
      '  int pivot = arr[high];',
      '  int i = low - 1;',
      '  for (int j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      swap(arr[i], arr[j]);',
      '    }',
      '  }',
      '  swap(arr[i+1], arr[high]);',
      '  return i + 1;',
      '}',
      'void quickSort(int arr[], int low, int high) {',
      '  if (low < high) {',
      '    int pi = partition(arr, low, high);',
      '    quickSort(arr, low, pi-1);',
      '    quickSort(arr, pi+1, high);',
      '  }',
      '}',
    ],
    python: [
      'def quick_sort(arr, low, high):',
      '    if low < high:',
      '        pi = partition(arr, low, high)',
      '        quick_sort(arr, low, pi-1)',
      '        quick_sort(arr, pi+1, high)',
      '',
      'def partition(arr, low, high):',
      '    pivot = arr[high]',
      '    i = low - 1',
      '    for j in range(low, high):',
      '        if arr[j] <= pivot:',
      '            i += 1',
      '            arr[i], arr[j] = arr[j], arr[i]',
      '    arr[i+1], arr[high] = arr[high], arr[i+1]',
      '    return i + 1',
    ],
  },
  'heap-sort': {
    cpp: [
      'void heapify(int arr[], int n, int i) {',
      '  int largest = i, l = 2*i+1, r = 2*i+2;',
      '  if (l < n && arr[l] > arr[largest]) largest = l;',
      '  if (r < n && arr[r] > arr[largest]) largest = r;',
      '  if (largest != i) {',
      '    swap(arr[i], arr[largest]);',
      '    heapify(arr, n, largest);',
      '  }',
      '}',
      'void heapSort(int arr[], int n) {',
      '  for (int i = n/2-1; i >= 0; i--)',
      '    heapify(arr, n, i);',
      '  for (int i = n-1; i > 0; i--) {',
      '    swap(arr[0], arr[i]);',
      '    heapify(arr, i, 0);',
      '  }',
      '}',
    ],
    python: [
      'def heap_sort(arr):',
      '    n = len(arr)',
      '    for i in range(n//2-1, -1, -1):',
      '        heapify(arr, n, i)',
      '    for i in range(n-1, 0, -1):',
      '        arr[0], arr[i] = arr[i], arr[0]',
      '        heapify(arr, i, 0)',
      '',
      'def heapify(arr, n, i):',
      '    largest = i',
      '    l, r = 2*i+1, 2*i+2',
      '    if l < n and arr[l] > arr[largest]: largest = l',
      '    if r < n and arr[r] > arr[largest]: largest = r',
      '    if largest != i:',
      '        arr[i], arr[largest] = arr[largest], arr[i]',
      '        heapify(arr, largest, i)',
    ],
  },
  'linear-search': {
    cpp: [
      'int linearSearch(int arr[], int n, int target) {',
      '  for (int i = 0; i < n; i++) {',
      '    if (arr[i] == target)',
      '      return i;',
      '  }',
      '  return -1;',
      '}',
    ],
    python: [
      'def linear_search(arr, target):',
      '    for i, val in enumerate(arr):',
      '        if val == target:',
      '            return i',
      '    return -1',
    ],
  },
  'binary-search': {
    cpp: [
      'int binarySearch(int arr[], int n, int target) {',
      '  int low = 0, high = n - 1;',
      '  while (low <= high) {',
      '    int mid = low + (high - low) / 2;',
      '    if (arr[mid] == target) return mid;',
      '    else if (arr[mid] < target) low = mid + 1;',
      '    else high = mid - 1;',
      '  }',
      '  return -1;',
      '}',
    ],
    python: [
      'def binary_search(arr, target):',
      '    low, high = 0, len(arr) - 1',
      '    while low <= high:',
      '        mid = (low + high) // 2',
      '        if arr[mid] == target:',
      '            return mid',
      '        elif arr[mid] < target:',
      '            low = mid + 1',
      '        else:',
      '            high = mid - 1',
      '    return -1',
    ],
  },
};
